# Generated by Django 5.2.6 on 2025-10-02 10:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('type_client', models.CharField(choices=[('grossiste', 'Grossiste'), ('detail', 'Détaillant'), ('particulier', 'Particulier')], max_length=20)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Dette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_restant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_echeance', models.DateField()),
                ('date_reglement', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('partiellement_paye', 'Partiellement payé'), ('paye', 'Payé'), ('en_retard', 'En retard')], default='en_cours', max_length=20)),
                ('nom_localite', models.CharField(blank=True, max_length=100)),
                ('bonus_accorde', models.BooleanField(default=False)),
                ('nombre_produits_bonus', models.PositiveIntegerField(default=0)),
                ('delai_bonus_heures', models.PositiveIntegerField(default=48)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_agent', models.CharField(choices=[('entrepot', 'Superviseur (entrepôt)'), ('terrain', 'Agent terrain')], max_length=10)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BonusAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_produits_recouverts', models.PositiveIntegerField(default=0)),
                ('total_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonus', to='core.agent')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_distribution', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent_terrain', models.ForeignKey(limit_choices_to={'type_agent': 'terrain'}, on_delete=django.db.models.deletion.CASCADE, related_name='distributions_recues', to='core.agent')),
                ('superviseur', models.ForeignKey(limit_choices_to={'type_agent': 'entrepot'}, on_delete=django.db.models.deletion.CASCADE, related_name='distributions_envoyees', to='core.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_facture', models.CharField(choices=[('entree', 'Facture Entrée - Entrepôt'), ('depot', 'Dépôt Agent - Superviseur')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fichier_facture', models.FileField(upload_to='factures_depots/')),
                ('date_depot', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_deposees', to='core.agent')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='LotEntrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_initiale', models.PositiveIntegerField()),
                ('quantite_restante', models.PositiveIntegerField()),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_reception', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('reference_lot', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
        ),
        migrations.CreateModel(
            name='DetailDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_gros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_detail', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.distributionagent')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lotentrepot')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementDette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('mode_paiement', models.CharField(choices=[('espece', 'Espèce'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('mobile', 'Paiement Mobile')], default='espece', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('bonus_genere', models.BooleanField(default=False)),
                ('nombre_produits_bonus', models.PositiveIntegerField(default=0)),
                ('dette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.dette')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('RECEPTION', 'Réception fournisseur'), ('DISTRIBUTION', 'Distribution superviseur'), ('VENTE', 'Vente client'), ('RETOUR', 'Retour stock')], max_length=20)),
                ('quantite', models.PositiveIntegerField()),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.agent')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lotentrepot')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('type_vente', models.CharField(choices=[('gros', 'Vente en Gros'), ('detail', 'Vente au Détail')], default='detail', max_length=10)),
                ('prix_vente_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('comptant', 'Paiement Comptant'), ('credit', 'Paiement à Crédit')], default='comptant', max_length=10)),
                ('date_vente', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(limit_choices_to={'type_agent': 'terrain'}, on_delete=django.db.models.deletion.CASCADE, to='core.agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('detail_distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.detaildistribution')),
            ],
        ),
        migrations.AddField(
            model_name='dette',
            name='vente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dette', to='core.vente'),
        ),
    ]
