# Generated by Django 5.2.6 on 2025-09-29 17:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('type_client', models.CharField(choices=[('grossiste', 'Grossiste'), ('detail', 'Détaillant'), ('particulier', 'Particulier')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_agent', models.CharField(choices=[('entrepot', 'Superviseur (entrepôt)'), ('terrain', 'Agent terrain')], max_length=10)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DistributionAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_distribution', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent_terrain', models.ForeignKey(limit_choices_to={'type_agent': 'terrain'}, on_delete=django.db.models.deletion.CASCADE, related_name='distributions_recues', to='core.agent')),
                ('superviseur', models.ForeignKey(limit_choices_to={'type_agent': 'entrepot'}, on_delete=django.db.models.deletion.CASCADE, related_name='distributions_envoyees', to='core.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_facture', models.CharField(choices=[('entree', 'Facture Entrée - Entrepôt'), ('depot', 'Dépôt Agent - Superviseur')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fichier_facture', models.FileField(upload_to='factures_depots/')),
                ('date_depot', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_deposees', to='core.agent')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='LotEntrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_initiale', models.PositiveIntegerField()),
                ('quantite_restante', models.PositiveIntegerField()),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_reception', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference_lot', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
        ),
        migrations.CreateModel(
            name='DetailDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_gros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_detail', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.distributionagent')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lotentrepot')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('RECEPTION', 'Réception fournisseur'), ('DISTRIBUTION', 'Distribution superviseur'), ('VENTE', 'Vente client'), ('RETOUR', 'Retour stock')], max_length=20)),
                ('quantite', models.PositiveIntegerField()),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.agent')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lotentrepot')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_vente_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_vente', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(limit_choices_to={'type_agent': 'terrain'}, on_delete=django.db.models.deletion.CASCADE, to='core.agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('detail_distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.detaildistribution')),
            ],
        ),
    ]
