# Generated by Django 5.2.6 on 2025-10-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='type_vente',
            field=models.CharField(choices=[('gros', 'Vente en Gros'), ('detail', 'Vente au Détail')], default='detail', max_length=10),
        ),
    ]
