# Generated by Django 5.2.6 on 2025-10-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='type_agent',
            field=models.CharField(choices=[('direction', 'Direction'), ('entrepot', 'Superviseur'), ('terrain', 'Agent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('grossiste', 'Grossiste'), ('detail', 'Détaillant'), ('particulier', 'Particulier')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dette',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('partiellement_paye', 'Partiellement payé'), ('paye', 'Payé'), ('en_retard', 'En retard')], default='en_cours', max_length=50),
        ),
        migrations.AlterField(
            model_name='distributionagent',
            name='type_distribution',
            field=models.CharField(choices=[('TERRAIN', 'Distribution à un agent '), ('AUTO', 'Auto-distribution ')], default='TERRAIN', max_length=50),
        ),
        migrations.AlterField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('entree', 'Facture Entrée - Entrepôt'), ('depot', 'Dépôt Agent - Superviseur')], max_length=50),
        ),
        migrations.AlterField(
            model_name='journalmodificationdistribution',
            name='type_action',
            field=models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('RESTAURATION', 'Restauration')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lotentrepot',
            name='reference_lot',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('RECEPTION', 'Réception fournisseur'), ('DISTRIBUTION', 'Distribution superviseur'), ('VENTE', 'Vente client'), ('RETOUR', 'Retour stock')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paiementdette',
            name='mode_paiement',
            field=models.CharField(choices=[('espece', 'Espèce'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('mobile', 'Paiement Mobile')], default='espece', max_length=50),
        ),
        migrations.AlterField(
            model_name='vente',
            name='mode_paiement',
            field=models.CharField(choices=[('comptant', 'Paiement Comptant'), ('credit', 'Paiement à Crédit')], default='comptant', max_length=50),
        ),
        migrations.AlterField(
            model_name='vente',
            name='type_vente',
            field=models.CharField(choices=[('gros', 'Vente en Gros'), ('detail', 'Vente au Détail')], default='detail', max_length=50),
        ),
    ]
