# Generated by Django 5.2.6 on 2025-10-02 12:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributionagent',
            options={'ordering': ['-date_distribution']},
        ),
        migrations.AddField(
            model_name='distributionagent',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributionagent',
            name='est_retroactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distributionagent',
            name='type_distribution',
            field=models.CharField(choices=[('TERRAIN', 'Distribution à un agent '), ('AUTO', 'Auto-distribution ')], default='TERRAIN', max_length=10),
        ),
        migrations.AlterField(
            model_name='agent',
            name='type_agent',
            field=models.CharField(choices=[('entrepot', 'Superviseur'), ('terrain', 'Agent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='distributionagent',
            name='agent_terrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributions_recues', to='core.agent'),
        ),
        migrations.AlterField(
            model_name='distributionagent',
            name='superviseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions_envoyees', to='core.agent'),
        ),
    ]
