# Generated by Django 5.2.6 on 2025-10-06 09:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_agent_telephone_alter_agent_type_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recouvrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_theorique_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant théorique total')),
                ('montant_recouvre', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant recouvré')),
                ('date_recouvrement', models.DateTimeField(default=django.utils.timezone.now)),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire du recouvrement')),
                ('statut', models.CharField(choices=[('PARTIEL', 'Partiellement payé'), ('COMPLET', 'Complètement payé')], default='PARTIEL', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recouvrements', to='core.agent')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recouvrements', to='core.distributionagent')),
                ('superviseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recouvrements_effectues', to='core.agent')),
            ],
        ),
    ]
