# Generated by Django 5.2.6 on 2025-10-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_distributionagent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributionagent',
            options={'ordering': ['-date_distribution'], 'verbose_name': 'Distribution', 'verbose_name_plural': 'Distributions'},
        ),
        migrations.AddField(
            model_name='distributionagent',
            name='nombre_produits_differents',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de produits différents'),
        ),
        migrations.AddField(
            model_name='distributionagent',
            name='quantite_totale',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité totale distribuée'),
        ),
        migrations.AddField(
            model_name='distributionagent',
            name='valeur_detail_totale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valeur totale (détail)'),
        ),
        migrations.AddField(
            model_name='distributionagent',
            name='valeur_gros_totale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valeur totale (gros)'),
        ),
    ]
