# Generated by Django 5.2.6 on 2025-10-02 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_distributionagent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detaildistribution',
            options={'verbose_name': 'Détail de distribution', 'verbose_name_plural': 'Détails de distribution'},
        ),
        migrations.AddField(
            model_name='detaildistribution',
            name='date_suppression',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detaildistribution',
            name='est_supprime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distributionagent',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='distributionagent',
            name='date_suppression',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AddField(
            model_name='distributionagent',
            name='derniere_modification_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions_modifiees', to=settings.AUTH_USER_MODEL, verbose_name='Dernière modification par'),
        ),
        migrations.AddField(
            model_name='distributionagent',
            name='est_supprime',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
        migrations.AddField(
            model_name='distributionagent',
            name='nombre_modifications',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de modifications'),
        ),
        migrations.AddField(
            model_name='distributionagent',
            name='raison_suppression',
            field=models.TextField(blank=True, verbose_name='Raison de la suppression'),
        ),
        migrations.CreateModel(
            name='JournalModificationDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('RESTAURATION', 'Restauration')], max_length=20)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('anciennes_valeurs', models.JSONField(blank=True, null=True)),
                ('nouvelles_valeurs', models.JSONField(blank=True, null=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.distributionagent')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal des modifications',
                'verbose_name_plural': 'Journal des modifications',
                'ordering': ['-date_action'],
            },
        ),
    ]
