# Generated by Django 5.2.6 on 2025-10-01 21:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_options_client_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotentrepot',
            name='date_enregistrement',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
