# Generated by Django 5.2.6 on 2025-10-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recouvrement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recouvrement',
            name='montant_recouvre',
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='montant_recouvre_detail',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant recouvré (détail)'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='montant_recouvre_gros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant recouvré (gros)'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='montant_recouvre_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant recouvré total'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='montant_theorique_detail',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant théorique (détail)'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='montant_theorique_gros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant théorique (gros)'),
        ),
    ]
