# Generated by Django 5.2.6 on 2025-10-01 22:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lotentrepot_date_enregistrement'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='mode_paiement',
            field=models.CharField(choices=[('comptant', 'Paiement Comptant'), ('credit', 'Paiement à Crédit')], default='comptant', max_length=10),
        ),
        migrations.CreateModel(
            name='BonusAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_produits_recouverts', models.PositiveIntegerField(default=0)),
                ('total_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonus', to='core.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Dette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_restant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_echeance', models.DateField()),
                ('date_reglement', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('partiellement_paye', 'Partiellement payé'), ('paye', 'Payé'), ('en_retard', 'En retard')], default='en_cours', max_length=20)),
                ('nom_localite', models.CharField(blank=True, max_length=100)),
                ('bonus_accorde', models.BooleanField(default=False)),
                ('nombre_produits_bonus', models.PositiveIntegerField(default=0)),
                ('delai_bonus_heures', models.PositiveIntegerField(default=48)),
                ('notes', models.TextField(blank=True)),
                ('vente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dette', to='core.vente')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementDette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('mode_paiement', models.CharField(choices=[('espece', 'Espèce'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('mobile', 'Paiement Mobile')], default='espece', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('bonus_genere', models.BooleanField(default=False)),
                ('nombre_produits_bonus', models.PositiveIntegerField(default=0)),
                ('dette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.dette')),
            ],
        ),
    ]
