# Generated by Django 5.2.6 on 2025-10-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_recouvrement_montant_recouvre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recouvrement',
            name='montant_theorique_total',
        ),
        migrations.AlterField(
            model_name='recouvrement',
            name='statut',
            field=models.CharField(choices=[('PARTIEL', 'non payé totalement'), ('COMPLET', 'Complètement payé')], default='PARTIEL', max_length=20),
        ),
    ]
