# Generated by Django 5.2.6 on 2025-10-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_detaildistribution_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotentrepot',
            name='date_upload_facture',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'upload de la facture"),
        ),
        migrations.AddField(
            model_name='lotentrepot',
            name='facture',
            field=models.FileField(blank=True, null=True, upload_to='factures_entrepot/%Y/%m/', verbose_name='Facture (optionnel)'),
        ),
    ]
