# Generated by Django 5.2.6 on 2025-10-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_recouvrement_montant_theorique_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recouvrement',
            name='montant_theorique_detail',
        ),
        migrations.RemoveField(
            model_name='recouvrement',
            name='montant_theorique_gros',
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='est_dernier_paiement',
            field=models.BooleanField(default=False, verbose_name='Dernier paiement'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='montant_du_ventes_detail',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant dû - Ventes Détail'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='montant_du_ventes_gros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant dû - Ventes Gros'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='montant_total_du',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant total dû'),
        ),
        migrations.AlterField(
            model_name='recouvrement',
            name='commentaire',
            field=models.TextField(blank=True, verbose_name='Commentaire du paiement'),
        ),
        migrations.AlterField(
            model_name='recouvrement',
            name='montant_recouvre_detail',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant recouvré détail'),
        ),
        migrations.AlterField(
            model_name='recouvrement',
            name='montant_recouvre_gros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant recouvré gros'),
        ),
        migrations.AlterField(
            model_name='recouvrement',
            name='montant_recouvre_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant total recouvré'),
        ),
        migrations.AlterField(
            model_name='recouvrement',
            name='statut',
            field=models.CharField(choices=[('PARTIEL', 'Paiement partiel'), ('COMPLET', 'Paiement complet'), ('FINALISE', 'Recouvrement finalisé')], default='PARTIEL', max_length=20),
        ),
    ]
