# Generated by Django 5.2.6 on 2025-10-07 01:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_recouvrement_montant_theorique_detail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recouvrement',
            options={'ordering': ['-date_recouvrement'], 'verbose_name': 'Recouvrement', 'verbose_name_plural': 'Recouvrements'},
        ),
        migrations.RemoveField(
            model_name='recouvrement',
            name='montant_recouvre_total',
        ),
        migrations.RemoveField(
            model_name='recouvrement',
            name='montant_total_du',
        ),
        migrations.RemoveField(
            model_name='recouvrement',
            name='statut',
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='est_supprime',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agent',
            name='type_agent',
            field=models.CharField(choices=[('direction', 'Direction'), ('superviseur', 'Superviseur'), ('terrain', 'Agent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recouvrement',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'type_agent': 'terrain'}, on_delete=django.db.models.deletion.CASCADE, to='core.agent', verbose_name='Agent à recouvrir'),
        ),
        migrations.AlterField(
            model_name='recouvrement',
            name='commentaire',
            field=models.TextField(blank=True, help_text='Contexte, conditions particulières, etc.', verbose_name='Commentaire sur le recouvrement'),
        ),
        migrations.AlterField(
            model_name='recouvrement',
            name='est_dernier_paiement',
            field=models.BooleanField(default=True, verbose_name='Dernier paiement pour cette distribution'),
        ),
        migrations.AlterField(
            model_name='recouvrement',
            name='montant_du_ventes_detail',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant dû (détail) basé sur ventes'),
        ),
        migrations.AlterField(
            model_name='recouvrement',
            name='montant_du_ventes_gros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant dû (gros) basé sur ventes'),
        ),
        migrations.AlterField(
            model_name='recouvrement',
            name='montant_recouvre_detail',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant recouvré (détail)'),
        ),
        migrations.AlterField(
            model_name='recouvrement',
            name='montant_recouvre_gros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant recouvré (gros)'),
        ),
        migrations.AlterField(
            model_name='recouvrement',
            name='superviseur',
            field=models.ForeignKey(limit_choices_to={'type_agent': 'entrepot'}, on_delete=django.db.models.deletion.CASCADE, related_name='recouvrements_effectues', to='core.agent', verbose_name='Superviseur recouvreur'),
        ),
    ]
