# Generated by Django 5.2.6 on 2025-10-07 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_recouvrement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recouvrement',
            name='distribution',
        ),
        migrations.RemoveField(
            model_name='recouvrement',
            name='est_dernier_paiement',
        ),
        migrations.RemoveField(
            model_name='recouvrement',
            name='montant_du_ventes_detail',
        ),
        migrations.RemoveField(
            model_name='recouvrement',
            name='montant_du_ventes_gros',
        ),
        migrations.RemoveField(
            model_name='recouvrement',
            name='montant_recouvre_detail',
        ),
        migrations.RemoveField(
            model_name='recouvrement',
            name='montant_recouvre_gros',
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='montant_recouvre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant recouvré'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='montant_total_ventes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total des ventes à recouvrir'),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='ventes',
            field=models.ManyToManyField(blank=True, related_name='recouvrements', to='core.vente', verbose_name='Ventes à recouvrir'),
        ),
        migrations.AlterField(
            model_name='recouvrement',
            name='commentaire',
            field=models.TextField(blank=True, verbose_name='Commentaire sur le recouvrement'),
        ),
        migrations.AlterField(
            model_name='recouvrement',
            name='superviseur',
            field=models.ForeignKey(limit_choices_to={'type_agent': 'superviseur'}, on_delete=django.db.models.deletion.CASCADE, related_name='recouvrements_effectues', to='core.agent', verbose_name='Superviseur recouvreur'),
        ),
    ]
