# Generated by Django 5.2.6 on 2025-10-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_recouvrement_distribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='type_agent',
            field=models.CharField(choices=[('direction', 'Direction'), ('entrepot', 'Superviseur'), ('terrain', 'Agent')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Recouvrement',
        ),
    ]
