# Generated by Django 5.2.6 on 2025-10-07 10:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_agent_type_agent_delete_recouvrement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recouvrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_recouvre', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant recouvré')),
                ('commentaire', models.TextField(blank=True)),
                ('date_recouvrement', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(limit_choices_to={'type_agent': 'terrain'}, on_delete=django.db.models.deletion.CASCADE, related_name='recouvrements', to='core.agent')),
                ('superviseur', models.ForeignKey(limit_choices_to={'type_agent': 'superviseur'}, on_delete=django.db.models.deletion.CASCADE, related_name='recouvrements_effectues', to='core.agent')),
            ],
            options={
                'verbose_name': 'Recouvrement',
                'verbose_name_plural': 'Recouvrements',
                'ordering': ['-date_recouvrement'],
            },
        ),
    ]
