# Generated by Django 5.2.5 on 2025-10-07 22:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_vente_options_vente_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('entree', 'Facture Entrée - Fournisseur'), ('depot', 'Dépôt Banque - Versement')], max_length=50),
        ),
        migrations.CreateModel(
            name='DepenseSuperviseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant de la dépense')),
                ('motif', models.CharField(max_length=255, verbose_name='Motif de la dépense')),
                ('commentaire', models.TextField(blank=True)),
                ('date_depense', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('superviseur', models.ForeignKey(limit_choices_to={'type_agent': 'superviseur'}, on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='core.agent')),
            ],
            options={
                'verbose_name': 'Dépense Superviseur',
                'verbose_name_plural': 'Dépenses Superviseur',
                'ordering': ['-date_depense'],
            },
        ),
        migrations.CreateModel(
            name='VersementBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_verse', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant versé à la banque')),
                ('preuve_versement', models.FileField(upload_to='versements_bancaires/', verbose_name='Photo du versement bancaire')),
                ('description', models.TextField(blank=True, verbose_name='Description (facultatif)')),
                ('date_versement', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('superviseur', models.ForeignKey(limit_choices_to={'type_agent': 'superviseur'}, on_delete=django.db.models.deletion.CASCADE, related_name='versements_bancaires', to='core.agent')),
            ],
            options={
                'verbose_name': 'Versement Bancaire',
                'verbose_name_plural': 'Versements Bancaires',
                'ordering': ['-date_versement'],
            },
        ),
    ]
