# Generated by Django 5.2.5 on 2025-10-07 23:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_facture_type_facture_depensesuperviseur_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'ordering': ['nom']},
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='adresse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
