# Generated by Django 5.2.6 on 2025-10-08 10:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_fournisseur_options_fournisseur_adresse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versementbancaire',
            options={'ordering': ['-date_fin_periode'], 'verbose_name': 'Versement Bancaire', 'verbose_name_plural': 'Versements Bancaires'},
        ),
        migrations.RemoveField(
            model_name='versementbancaire',
            name='date_versement',
        ),
        migrations.RemoveField(
            model_name='versementbancaire',
            name='description',
        ),
        migrations.RemoveField(
            model_name='versementbancaire',
            name='montant_verse',
        ),
        migrations.RemoveField(
            model_name='versementbancaire',
            name='preuve_versement',
        ),
        migrations.AddField(
            model_name='versementbancaire',
            name='date_debut_periode',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Début de la période'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='versementbancaire',
            name='date_fin_periode',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fin de la période'),
        ),
        migrations.AddField(
            model_name='versementbancaire',
            name='details_depenses',
            field=models.TextField(blank=True, verbose_name='Détail des dépenses effectuées'),
        ),
        migrations.AddField(
            model_name='versementbancaire',
            name='facture',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='versement_associe', to='core.facture', verbose_name='Facture associée'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='versementbancaire',
            name='montant_depenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total des dépenses'),
        ),
        migrations.AddField(
            model_name='versementbancaire',
            name='montant_total_recouvre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total recouvré'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='versementbancaire',
            name='preuve_depenses',
            field=models.FileField(blank=True, null=True, upload_to='preuves_depenses/', verbose_name='Justificatifs des dépenses'),
        ),
        migrations.DeleteModel(
            name='DepenseSuperviseur',
        ),
    ]
