# Generated by Django 5.2.6 on 2025-10-08 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_versementbancaire_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versementbancaire',
            options={'ordering': ['-date_versement_reelle'], 'verbose_name': 'Versement Bancaire', 'verbose_name_plural': 'Versements Bancaires'},
        ),
        migrations.AddField(
            model_name='versementbancaire',
            name='date_versement_reelle',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Date à laquelle le versement a été effectué (peut être différente de la date d'enregistrement)", verbose_name='Date réelle du versement'),
        ),
        migrations.AlterField(
            model_name='versementbancaire',
            name='date_fin_periode',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fin de la période (date du versement)'),
        ),
    ]
