# Generated by Django 5.2.6 on 2025-10-09 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_versementbancaire_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agent'),
        ),
    ]
