# Generated by Django 5.2.6 on 2025-10-09 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_vente_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'type_agent__in': ['terrain', 'entrepot']}, on_delete=django.db.models.deletion.CASCADE, to='core.agent'),
        ),
    ]
