# Generated by Django 5.2.6 on 2025-10-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_vente_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='ajustement_solde',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ajustement manuel du solde (+/- FCFA)', max_digits=12),
        ),
    ]
