# Generated by Django 5.2.7 on 2025-10-25 22:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_agent_ajustement_solde'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='date_expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date d’expiration (stagiaire)'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='type_agent',
            field=models.CharField(choices=[('direction', 'Direction'), ('entrepot', 'Superviseur'), ('terrain', 'Agent'), ('stagiaire', 'Stagiaire')], max_length=50),
        ),
        migrations.AlterField(
            model_name='distributionagent',
            name='type_distribution',
            field=models.CharField(choices=[('TERRAIN', 'Distribution à un agent '), ('AUTO', 'Auto-distribution '), ('STAGIAIRE', 'Distribution à un stagiaire')], default='TERRAIN', max_length=50),
        ),
    ]
