# Generated by Django 5.2.7 on 2025-11-05 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_agent_date_creation_agent_date_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotentrepot',
            name='fournisseur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fournisseur', verbose_name='Fournisseur (optionnel)'),
        ),
    ]
