# Generated by Django 5.2.7 on 2025-11-05 22:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_lotentrepot_fournisseur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vente',
            options={},
        ),
        migrations.RemoveField(
            model_name='vente',
            name='detail_distribution',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='prix_vente_unitaire',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='quantite',
        ),
        migrations.AddField(
            model_name='vente',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='est_complete',
            field=models.BooleanField(default=True, verbose_name='Vente complètement honorée'),
        ),
        migrations.AddField(
            model_name='vente',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vente',
            name='prix_vente_moyen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix de vente moyen pondéré'),
        ),
        migrations.AddField(
            model_name='vente',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.produit', verbose_name='Produit vendu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vente',
            name='quantite_demandee',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité demandée'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vente',
            name='quantite_reellement_vendue',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité réellement vendue'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agent'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='date_vente',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vente',
            name='mode_paiement',
            field=models.CharField(choices=[('comptant', 'Paiement comptant'), ('credit', 'Paiement à crédit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vente',
            name='type_vente',
            field=models.CharField(choices=[('gros', 'Vente en gros'), ('detail', 'Vente au détail')], max_length=20),
        ),
        migrations.CreateModel(
            name='DetailVenteFIFO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('detail_distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.detaildistribution')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_fifo', to='core.vente')),
            ],
            options={
                'verbose_name': 'Détail de vente FIFO',
                'verbose_name_plural': 'Détails de vente FIFO',
            },
        ),
    ]
