# Generated by Django 5.2.7 on 2025-11-05 22:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_vente_options_remove_vente_detail_distribution_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vente',
            options={'ordering': ['-date_vente'], 'verbose_name': 'Vente', 'verbose_name_plural': 'Ventes'},
        ),
        migrations.RemoveField(
            model_name='vente',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='est_complete',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='montant_total',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='prix_vente_moyen',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='quantite_demandee',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='quantite_reellement_vendue',
        ),
        migrations.AddField(
            model_name='vente',
            name='detail_distribution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.detaildistribution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vente',
            name='prix_vente_unitaire',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vente',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vente',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'type_agent__in': ['terrain', 'entrepot']}, on_delete=django.db.models.deletion.CASCADE, to='core.agent'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='vente',
            name='date_vente',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la vente'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='mode_paiement',
            field=models.CharField(choices=[('comptant', 'Paiement Comptant'), ('credit', 'Paiement à Crédit')], default='comptant', max_length=50),
        ),
        migrations.AlterField(
            model_name='vente',
            name='type_vente',
            field=models.CharField(choices=[('gros', 'Vente en Gros'), ('detail', 'Vente au Détail')], default='detail', max_length=50),
        ),
        migrations.DeleteModel(
            name='DetailVenteFIFO',
        ),
    ]
