# Generated by Django 5.2.7 on 2025-11-06 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_vente_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recouvrement',
            name='superviseur',
            field=models.ForeignKey(limit_choices_to={'type_agent': 'entrepot'}, on_delete=django.db.models.deletion.CASCADE, related_name='recouvrements_effectues', to='core.agent'),
        ),
    ]
