# Generated by Django 5.2.7 on 2025-11-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_recouvrement_superviseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='date_mise_service',
            field=models.DateTimeField(blank=True, help_text='Date à laquelle le stagiaire a commencé son activité', null=True, verbose_name='Date de mise en service'),
        ),
    ]
