# Generated by Django 5.2.7 on 2025-11-08 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_agent_date_mise_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='stagiaire',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_agent': 'stagiaire'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_realisees', to='core.agent'),
        ),
    ]
