# Generated by Django 5.2.7 on 2025-11-09 22:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_vente_stagiaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versementbancaire',
            name='date_debut_periode',
        ),
        migrations.RemoveField(
            model_name='versementbancaire',
            name='date_fin_periode',
        ),
        migrations.RemoveField(
            model_name='versementbancaire',
            name='facture',
        ),
        migrations.RemoveField(
            model_name='versementbancaire',
            name='montant_depenses',
        ),
        migrations.RemoveField(
            model_name='versementbancaire',
            name='montant_total_recouvre',
        ),
        migrations.RemoveField(
            model_name='versementbancaire',
            name='preuve_depenses',
        ),
        migrations.AddField(
            model_name='versementbancaire',
            name='montant_verse',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant versé'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='versementbancaire',
            name='type_versement',
            field=models.CharField(choices=[('vente', 'Versement lié à la vente'), ('autre', 'Versement hors vente/recouvrement')], default='vente', help_text='Indique si le versement est lié à la vente ou autre', max_length=20, verbose_name='Type de versement'),
        ),
        migrations.AlterField(
            model_name='versementbancaire',
            name='date_versement_reelle',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date réelle du versement'),
        ),
        migrations.AlterField(
            model_name='versementbancaire',
            name='details_depenses',
            field=models.TextField(blank=True, verbose_name='Notes générales sur les dépenses'),
        ),
        migrations.AlterField(
            model_name='versementbancaire',
            name='superviseur',
            field=models.ForeignKey(limit_choices_to={'type_agent': 'entrepot'}, on_delete=django.db.models.deletion.CASCADE, related_name='versements_bancaires', to='core.agent'),
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_versement', models.CharField(choices=[('vente', 'Versement lié à la vente'), ('autre', 'Versement hors vente/recouvrement')], default='vente', help_text='Détermine si la dépense impacte le solde des ventes', max_length=20, verbose_name='Type de versement associé')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant de la dépense')),
                ('description', models.TextField(verbose_name='Détails de la dépense')),
                ('categorie', models.CharField(choices=[('transport', 'Transport'), ('communication', 'Communication'), ('frais_bancaires', 'Frais Bancaires'), ('materiel', 'Matériel'), ('autres', 'Autres Dépenses')], default='autres', max_length=50, verbose_name='Catégorie de dépense')),
                ('date_depense', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la dépense')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='justificatifs_depenses/%Y/%m/', verbose_name='Justificatif de dépense')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('superviseur', models.ForeignKey(limit_choices_to={'type_agent': 'entrepot'}, on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='core.agent')),
                ('versement', models.ForeignKey(blank=True, help_text='Lien vers le versement si applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='core.versementbancaire', verbose_name='Versement associé')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense'],
            },
        ),
    ]
