# Generated by Django 5.2.7 on 2025-11-09 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_versementbancaire_date_debut_periode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versementbancaire',
            name='details_depenses',
        ),
    ]
