# Generated by Django 5.2.7 on 2025-11-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_versementbancaire_details_depenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='versementbancaire',
            name='details_depenses',
            field=models.TextField(blank=True, verbose_name='Notes générales sur les dépenses'),
        ),
    ]
