# Generated by Django 5.2.7 on 2025-11-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_versementbancaire_details_depenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotentrepot',
            name='quantite_initiale',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lotentrepot',
            name='quantite_restante',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
