# Generated by Django 5.2.7 on 2025-11-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_lotentrepot_quantite_initiale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionagent',
            name='quantite_totale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantité totale distribuée'),
        ),
    ]
