# Generated by Django 5.2.7 on 2025-11-16 02:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_distributionagent_quantite_totale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
