# Generated by Django 5.2.7 on 2025-11-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_vente_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaildistribution',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantité totale distribuée'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantité totale distribuée'),
        ),
    ]
