# Generated by Django 5.2.7 on 2025-11-16 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_detaildistribution_quantite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_perdue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('date_perte', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertes', to='core.lotentrepot')),
            ],
        ),
    ]
