# Generated by Django 5.2.7 on 2025-11-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_perte'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotentrepot',
            name='valeur_stock_initiale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
