# Generated by Django 5.2.7 on 2025-11-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_mouvementstock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaildistribution',
            name='specification',
            field=models.CharField(blank=True, max_length=200, verbose_name='Spécification (forme, présentation, etc.)'),
        ),
    ]
