# Generated by Django 5.2.7 on 2025-11-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_detaildistribution_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='specification',
            field=models.CharField(blank=True, max_length=200, verbose_name='Spécification du produit'),
        ),
    ]
