# Generated by Django 5.2.7 on 2025-11-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_vente_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='date_suppression',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AddField(
            model_name='vente',
            name='est_supprime',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
        migrations.AddField(
            model_name='vente',
            name='raison_suppression',
            field=models.TextField(blank=True, verbose_name='Raison de la suppression'),
        ),
    ]
