# Generated by Django 5.2.7 on 2025-11-22 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_perte_date_modification_perte_est_modifiee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='date_suppression',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='est_supprime',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='raison_suppression',
        ),
    ]
