# Generated by Django 5.2.7 on 2025-11-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_vente_date_suppression_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perte',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='perte',
            name='est_modifiee',
        ),
        migrations.RemoveField(
            model_name='perte',
            name='quantite_perdue_originale',
        ),
        migrations.AlterField(
            model_name='perte',
            name='date_perte',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
