# Generated by Django 5.2.7 on 2025-11-22 01:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_perte_date_modification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perte',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perte',
            name='est_modifiee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perte',
            name='quantite_perdue_originale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantité perdue initiale'),
        ),
        migrations.AlterField(
            model_name='perte',
            name='date_perte',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
