# Generated by Django 5.2.7 on 2025-11-22 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_perte_date_modification_perte_est_modifiee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depense',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='justificatif',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='superviseur',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='type_versement',
        ),
        migrations.RemoveField(
            model_name='versementbancaire',
            name='details_depenses',
        ),
        migrations.AddField(
            model_name='versementbancaire',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Description du versement'),
        ),
        migrations.AddField(
            model_name='versementbancaire',
            name='recu',
            field=models.FileField(blank=True, null=True, upload_to='justificatifs_depenses/%Y/%m/', verbose_name='Justificatif de dépense'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='versement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='core.versementbancaire'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='versementbancaire',
            name='type_versement',
            field=models.CharField(choices=[('vente', 'Versement lié à la vente'), ('autre', 'Versement hors vente')], default='vente', max_length=20, verbose_name='Type de versement'),
        ),
    ]
