# Generated by Django 5.2.7 on 2025-11-22 20:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_depense_categorie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versementbancaire',
            options={'ordering': ['-date_versement_reelle']},
        ),
        migrations.RenameField(
            model_name='versementbancaire',
            old_name='notes',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='versementbancaire',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='versementbancaire',
            name='montant_verse',
        ),
        migrations.RemoveField(
            model_name='versementbancaire',
            name='type_versement',
        ),
        migrations.AddField(
            model_name='depense',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='versementbancaire',
            name='montant_hors_vente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant hors vente'),
        ),
        migrations.AddField(
            model_name='versementbancaire',
            name='montant_vente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant provenant de la vente'),
        ),
        migrations.AlterField(
            model_name='versementbancaire',
            name='recu',
            field=models.FileField(blank=True, null=True, upload_to='recu_versement/%Y/%m/', verbose_name='Justificatif du versement'),
        ),
    ]
