# Generated by Django 5.2.7 on 2025-11-23 01:47

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_versementbancaire_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Détails de la dépense'),
        ),
        migrations.AlterField(
            model_name='versementbancaire',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Description du versement'),
        ),
    ]
