# Generated by Django 5.2.7 on 2025-11-23 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_depense_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versementbancaire',
            name='recu',
        ),
        migrations.CreateModel(
            name='RecuVersement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='recu_versement/%Y/%m/', verbose_name='Fichier reçu')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description du reçu')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('versement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recus', to='core.versementbancaire', verbose_name='Versement associé')),
            ],
            options={
                'verbose_name': 'Reçu de versement',
                'verbose_name_plural': 'Reçus de versement',
                'ordering': ['-date_upload'],
            },
        ),
    ]
