# Generated by Django 5.2.7 on 2025-11-26 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_versementbancaire_recu_recuversement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recuversement',
            name='versement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recus', to='core.versementbancaire', verbose_name='Versement associé'),
        ),
    ]
