# Generated by Django 5.2.7 on 2025-11-27 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_recuversement_versement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotentrepot',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='core.produit'),
        ),
    ]
