# Generated by Django 5.2.7 on 2025-11-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_lotentrepot_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dette',
            name='bonus_accorde',
        ),
        migrations.RemoveField(
            model_name='dette',
            name='delai_bonus_heures',
        ),
        migrations.RemoveField(
            model_name='dette',
            name='nombre_produits_bonus',
        ),
        migrations.RemoveField(
            model_name='paiementdette',
            name='bonus_genere',
        ),
        migrations.RemoveField(
            model_name='paiementdette',
            name='nombre_produits_bonus',
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='bonus_accorde',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recouvrement',
            name='montant_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
