# Generated by Django 5.2.7 on 2025-11-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_remove_dette_bonus_accorde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='date_suppression',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AddField(
            model_name='vente',
            name='est_supprime',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
    ]
