# Generated by Django 5.2.7 on 2025-11-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_vente_date_suppression_vente_est_supprime'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaildistribution',
            name='quantite_vendue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
