# Generated by Django 5.2.7 on 2025-11-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_detaildistribution_quantite_vendue'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='ancienne_vente',
            field=models.BooleanField(default=False),
        ),
    ]
