# Generated by Django 5.2.7 on 2025-11-30 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_vente_ancienne_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='recouvrement',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.vente'),
        ),
    ]
