# Generated by Django 5.2.7 on 2025-11-30 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_recouvrement_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recouvrement',
            name='superviseur',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_agent': 'entrepot'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recouvrements_effectues', to='core.agent'),
        ),
    ]
