# Generated by Django 5.2.7 on 2025-12-16 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_recouvrement_superviseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='versement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recus_bancaires', to='core.versementbancaire'),
        ),
    ]
