# Generated by Django 5.2.7 on 2025-12-19 17:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_facture_versement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant payé')),
                ('est_paiement_final', models.BooleanField(default=False, verbose_name='Paiement final (clôture de la dette)')),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('facture', models.FileField(blank=True, null=True, upload_to='factures_paiement_fournisseur/%Y/%m/', verbose_name='Reçu fournisseur')),
                ('date_upload_facture', models.DateTimeField(blank=True, null=True)),
                ('est_valide', models.BooleanField(default=False, verbose_name='Paiement validé')),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('donne_par', models.ForeignKey(limit_choices_to={'agent__type_agent': 'direction'}, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_donnes', to=settings.AUTH_USER_MODEL, verbose_name='Autorisé par (Direction)')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_recus', to='core.fournisseur')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_fournisseur', to='core.lotentrepot', verbose_name='Lot concerné')),
                ('paye_par', models.ForeignKey(limit_choices_to={'type_agent': 'entrepot'}, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_effectues', to='core.agent', verbose_name='Payé par (Superviseur)')),
            ],
            options={
                'verbose_name': 'Paiement fournisseur',
                'verbose_name_plural': 'Paiements fournisseurs',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
