# Generated by Django 5.2.7 on 2025-12-19 18:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_paiementfournisseur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiementfournisseur',
            options={'ordering': ['-date_paiement', '-date_creation'], 'verbose_name': 'Paiement fournisseur', 'verbose_name_plural': 'Paiements fournisseurs'},
        ),
        migrations.RemoveField(
            model_name='paiementfournisseur',
            name='date_upload_facture',
        ),
        migrations.RemoveField(
            model_name='paiementfournisseur',
            name='description',
        ),
        migrations.RemoveField(
            model_name='paiementfournisseur',
            name='donne_par',
        ),
        migrations.RemoveField(
            model_name='paiementfournisseur',
            name='est_paiement_final',
        ),
        migrations.RemoveField(
            model_name='paiementfournisseur',
            name='facture',
        ),
        migrations.RemoveField(
            model_name='paiementfournisseur',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='paiementfournisseur',
            name='paye_par',
        ),
        migrations.AddField(
            model_name='paiementfournisseur',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='paiementfournisseur',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='paiements_fournisseurs/%Y/%m/', verbose_name='Justificatif'),
        ),
        migrations.AddField(
            model_name='paiementfournisseur',
            name='lots',
            field=models.ManyToManyField(blank=True, related_name='paiements_associes', to='core.lotentrepot', verbose_name='Lots concernés'),
        ),
        migrations.AddField(
            model_name='paiementfournisseur',
            name='mode_paiement',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque'), ('MOBILE', 'Mobile Money'), ('AUTRE', 'Autre')], default='ESPECES', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='paiementfournisseur',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence/Numéro'),
        ),
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='date_paiement',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date du paiement'),
        ),
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='est_valide',
            field=models.BooleanField(default=True, verbose_name='Paiement validé'),
        ),
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.fournisseur', verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
