# Generated by Django 5.2.7 on 2025-12-19 19:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_paiementfournisseur_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiementfournisseur',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RenameField(
            model_name='paiementfournisseur',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='paiementfournisseur',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='paiementfournisseur',
            name='date_paiement',
        ),
        migrations.RemoveField(
            model_name='paiementfournisseur',
            name='est_valide',
        ),
        migrations.RemoveField(
            model_name='paiementfournisseur',
            name='justificatif',
        ),
        migrations.RemoveField(
            model_name='paiementfournisseur',
            name='lots',
        ),
        migrations.RemoveField(
            model_name='paiementfournisseur',
            name='mode_paiement',
        ),
        migrations.AddField(
            model_name='paiementfournisseur',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paiementfournisseur',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.lotentrepot'),
        ),
        migrations.AddField(
            model_name='paiementfournisseur',
            name='mode',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque'), ('MOBILE', 'Mobile Money')], default='ESPECES', max_length=20),
        ),
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.fournisseur'),
        ),
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
