# Generated by Django 5.2.7 on 2025-12-19 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_paiementfournisseur_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotentrepot',
            name='fournisseur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='core.fournisseur', verbose_name='Fournisseur (optionnel)'),
        ),
    ]
