# Generated by Django 5.2.7 on 2025-12-19 20:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_lotentrepot_fournisseur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiementfournisseur',
            options={'ordering': ['-date_paiement', '-created_at'], 'verbose_name': 'Paiement fournisseur', 'verbose_name_plural': 'Paiements fournisseurs'},
        ),
        migrations.RemoveField(
            model_name='paiementfournisseur',
            name='date',
        ),
        migrations.AddField(
            model_name='paiementfournisseur',
            name='date_paiement',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de paiement'),
        ),
        migrations.AddField(
            model_name='paiementfournisseur',
            name='date_suppression',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AddField(
            model_name='paiementfournisseur',
            name='est_supprime',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
        migrations.AddField(
            model_name='paiementfournisseur',
            name='raison_suppression',
            field=models.TextField(blank=True, verbose_name='Raison de la suppression'),
        ),
        migrations.AddField(
            model_name='paiementfournisseur',
            name='superviseur',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_agent__in': ['direction', 'entrepot']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_fournisseurs', to='core.agent', verbose_name='Superviseur responsable'),
        ),
        migrations.AddField(
            model_name='paiementfournisseur',
            name='supprime_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_fournisseurs_supprimes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiementfournisseur',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_fournisseurs_crees', to=settings.AUTH_USER_MODEL),
        ),
    ]
