# Generated by Django 5.2.7 on 2025-12-20 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_paiementfournisseur_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiementfournisseur',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='paiementfournisseur',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='paiementfournisseur',
            name='raison_suppression',
        ),
        migrations.RemoveField(
            model_name='paiementfournisseur',
            name='reference',
        ),
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='date_paiement',
            field=models.DateField(verbose_name='Date du paiement'),
        ),
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='date_suppression',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='est_supprime',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='lot',
            field=models.ForeignKey(blank=True, help_text='Optionnel : paiement rattaché à un lot précis', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.lotentrepot'),
        ),
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='superviseur',
            field=models.ForeignKey(limit_choices_to={'type_agent': 'entrepot'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_fournisseurs', to='core.agent', verbose_name='Superviseur responsable'),
        ),
    ]
