# Generated by Django 5.2.7 on 2025-12-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_remove_paiementfournisseur_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='est_actif',
            field=models.BooleanField(default=True, help_text='Agent actif sur la plateforme'),
        ),
    ]
