# Generated by Django 5.2.7 on 2025-12-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_agent_est_actif'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facture',
        ),
    ]
