# Generated by Django 5.2.7 on 2025-12-22 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_delete_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotentrepot',
            name='date_upload_facture',
        ),
        migrations.RemoveField(
            model_name='lotentrepot',
            name='facture',
        ),
        migrations.CreateModel(
            name='FactureLotEntrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='factures_entrepot/%Y/%m/')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, help_text='Montant payé pour ce justificatif', max_digits=10, null=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='core.lotentrepot')),
            ],
        ),
    ]
