# Generated by Django 5.2.7 on 2025-12-22 17:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_remove_lotentrepot_date_upload_facture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotentrepot',
            name='date_upload_facture',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'upload de la facture"),
        ),
        migrations.AddField(
            model_name='lotentrepot',
            name='facture',
            field=models.FileField(blank=True, null=True, upload_to='factures_entrepot/%Y/%m/', verbose_name='Facture (optionnel)'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_facture', models.CharField(choices=[('entree', 'Facture Entrée - Fournisseur'), ('depot', 'Dépôt Banque - Versement')], max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fichier_facture', models.FileField(upload_to='factures_depots/')),
                ('date_depot', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_deposees', to='core.agent')),
                ('versement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recus_bancaires', to='core.versementbancaire')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.DeleteModel(
            name='FactureLotEntrepot',
        ),
    ]
