# Generated by Django 5.2.7 on 2025-12-22 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_lotentrepot_date_upload_facture_lotentrepot_facture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotentrepot',
            name='date_upload_facture',
        ),
        migrations.RemoveField(
            model_name='lotentrepot',
            name='facture',
        ),
        migrations.CreateModel(
            name='FactureLotEntrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='factures_entrepot/%Y/%m/')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='core.lotentrepot')),
            ],
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
    ]
