# Generated by Django 5.2.7 on 2025-12-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_remove_lotentrepot_date_upload_facture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='date_fin_contrat',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin de contrat'),
        ),
        migrations.AddField(
            model_name='agent',
            name='marche_affectation',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Marché d'affectation"),
        ),
        migrations.AddField(
            model_name='agent',
            name='quartier',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Quartier d'affectation"),
        ),
        migrations.AddField(
            model_name='agent',
            name='type_contrat',
            field=models.CharField(choices=[('prestation', 'Contrat de prestation'), ('stage', 'Stage'), ('cdd', 'CDD'), ('cdi', 'CDI')], default='prestation', max_length=20, verbose_name='Type de contrat'),
        ),
    ]
