# Generated by Django 5.2.7 on 2025-12-23 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_agent_date_fin_contrat_agent_marche_affectation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClotureMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(verbose_name='Année de référence')),
                ('mois', models.IntegerField(verbose_name='Mois de référence')),
                ('date_debut_periode', models.DateField(verbose_name='Début réel de la période')),
                ('date_fin_periode', models.DateField(verbose_name='Fin réelle de la période')),
                ('solde_ouverture', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Solde d'ouverture")),
                ('solde_cloture', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Solde de clôture')),
                ('est_cloture', models.BooleanField(default=False, verbose_name='Clôture validée')),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation de la clôture')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('cloture_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures_validees', to=settings.AUTH_USER_MODEL, verbose_name='Clôturée par')),
                ('superviseur', models.ForeignKey(limit_choices_to={'type_agent': 'entrepot'}, on_delete=django.db.models.deletion.CASCADE, related_name='clotures_mensuelles', to='core.agent')),
            ],
            options={
                'verbose_name': 'Clôture mensuelle',
                'verbose_name_plural': 'Clôtures mensuelles',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('superviseur', 'annee', 'mois')},
            },
        ),
    ]
