# Generated by Django 5.2.7 on 2025-12-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_cloturemensuelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloturemensuelle',
            name='ecart_post_cloture',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Écart après clôture'),
        ),
    ]
