# Generated by Django 5.2.7 on 2025-12-29 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_cloturemensuelle_ecart_post_cloture'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjustementSolde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motif', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustements_solde', to='core.agent')),
                ('cloture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustements', to='core.cloturemensuelle')),
            ],
        ),
    ]
