# Generated by Django 5.2.7 on 2026-01-02 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_ajustementsolde'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='superviseur',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_agent': 'entrepot'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_geres', to='core.agent'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='type_agent',
            field=models.CharField(choices=[('direction', 'Direction'), ('rot', 'Responsable Opérations'), ('entrepot', 'Superviseur'), ('terrain', 'Agent'), ('stagiaire', 'Stagiaire')], max_length=50),
        ),
        migrations.CreateModel(
            name='AffectationLotSuperviseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
                ('attribue_par', models.ForeignKey(limit_choices_to={'type_agent': 'rot'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_realisees', to='core.agent')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lotentrepot')),
                ('superviseur', models.ForeignKey(limit_choices_to={'type_agent': 'entrepot'}, on_delete=django.db.models.deletion.CASCADE, related_name='lots_affectes', to='core.agent')),
            ],
        ),
        migrations.CreateModel(
            name='AffectationLotAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(limit_choices_to={'type_agent': 'terrain'}, on_delete=django.db.models.deletion.CASCADE, to='core.agent')),
                ('affectation_superviseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_agents', to='core.affectationlotsuperviseur')),
            ],
        ),
    ]
