# Generated by Django 5.2.7 on 2026-01-03 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_agent_superviseur_alter_agent_type_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotentrepot',
            name='receptionne_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_receptionnes', to='core.agent'),
        ),
    ]
