# Generated by Django 5.2.7 on 2026-01-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_lotentrepot_receptionne_par'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detaildistribution',
            name='date_suppression',
        ),
        migrations.RemoveField(
            model_name='detaildistribution',
            name='est_supprime',
        ),
        migrations.RemoveField(
            model_name='distributionagent',
            name='date_suppression',
        ),
        migrations.RemoveField(
            model_name='distributionagent',
            name='derniere_modification_par',
        ),
        migrations.RemoveField(
            model_name='distributionagent',
            name='est_supprime',
        ),
        migrations.RemoveField(
            model_name='distributionagent',
            name='nombre_modifications',
        ),
        migrations.RemoveField(
            model_name='distributionagent',
            name='raison_suppression',
        ),
    ]
