# Generated by Django 5.2.7 on 2026-01-03 21:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_remove_detaildistribution_date_suppression_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecouvrementSuperviseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant remis au ROT')),
                ('mode_remise', models.CharField(choices=[('espece', 'Espèces'), ('mobile', 'Mobile money'), ('cheque', 'Chèque')], default='espece', max_length=50)),
                ('commentaire', models.TextField(blank=True)),
                ('date_recouvrement', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('rot', models.ForeignKey(limit_choices_to={'type_agent': 'rot'}, on_delete=django.db.models.deletion.CASCADE, related_name='recouvrements_superviseurs', to='core.agent')),
                ('superviseur', models.ForeignKey(limit_choices_to={'type_agent': 'entrepot'}, on_delete=django.db.models.deletion.CASCADE, related_name='recouvrements_rot', to='core.agent')),
            ],
            options={
                'verbose_name': 'Recouvrement superviseur',
                'verbose_name_plural': 'Recouvrements superviseurs',
                'ordering': ['-date_recouvrement'],
            },
        ),
        migrations.DeleteModel(
            name='AffectationLotAgent',
        ),
    ]
