# Generated by Django 5.2.7 on 2026-01-03 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_recouvrementsuperviseur_delete_affectationlotagent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recouvrementsuperviseur',
            name='mode_remise',
        ),
    ]
