# Generated by Django 5.2.7 on 2026-01-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_remove_recouvrementsuperviseur_mode_remise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affectationlotsuperviseur',
            old_name='quantite',
            new_name='quantite_initiale',
        ),
        migrations.AddField(
            model_name='affectationlotsuperviseur',
            name='quantite_restante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='affectationlotsuperviseur',
            unique_together={('lot', 'superviseur')},
        ),
    ]
