# Generated by Django 5.2.7 on 2026-01-04 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_rename_quantite_affectationlotsuperviseur_quantite_initiale_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='affectationlotsuperviseur',
            unique_together=set(),
        ),
    ]
