# Generated by Django 5.2.7 on 2026-01-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_affectationlotsuperviseur_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='poids_unitaire_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Poids standard d’une unité (carton/sac). Laisser vide si produit non conditionné.', max_digits=6, null=True),
        ),
    ]
