# Generated by Django 5.2.7 on 2026-01-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_produit_poids_unitaire_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotentrepot',
            name='prix_achat_unitaire',
            field=models.DecimalField(decimal_places=2, help_text='Prix par unité fournisseur (carton / sac OU kg si non conditionné)', max_digits=10),
        ),
    ]
