# Generated by Django 5.2.7 on 2026-01-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_alter_lotentrepot_prix_achat_unitaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='type_agent',
            field=models.CharField(choices=[('direction', 'Direction'), ('rot', 'Responsable Opérations'), ('entrepot', 'Superviseur'), ('terrain', 'Agent'), ('agent_gros', 'Agent (Vente en Gros)'), ('stagiaire', 'Stagiaire')], max_length=50),
        ),
    ]
