# Generated by Django 5.2.7 on 2026-01-15 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_alter_agent_type_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='effectue_par',
            field=models.ForeignKey(blank=True, help_text='Agent ayant réellement effectué la dépense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_effectuees', to='core.agent'),
        ),
        migrations.AddField(
            model_name='versementbancaire',
            name='effectue_par',
            field=models.ForeignKey(blank=True, help_text='Agent ayant réellement effectué le versement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements_effectues', to='core.agent'),
        ),
    ]
