# Generated by Django 5.2.7 on 2026-01-15 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_depense_effectue_par_versementbancaire_effectue_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versementbancaire',
            name='effectue_par',
            field=models.ForeignKey(blank=True, help_text='ROT ayant réellement effectué le versement', limit_choices_to={'type_agent': 'rot'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements_effectues', to='core.agent'),
        ),
        migrations.AlterField(
            model_name='versementbancaire',
            name='superviseur',
            field=models.ForeignKey(blank=True, help_text='(OBSOLÈTE) Superviseur source du cash', limit_choices_to={'type_agent': 'entrepot'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements_bancaires', to='core.agent'),
        ),
    ]
