# Generated by Django 5.2.7 on 2026-01-20 00:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_alter_versementbancaire_effectue_par_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegleSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_agent', models.CharField(choices=[('terrain', 'Agent terrain (mamy)'), ('agent_gros', 'Agent gros'), ('superviseur', 'Superviseur')], max_length=20, unique=True)),
                ('salaire_base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('incentive_par_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('incentive_par_carton', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incentive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salaire_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('genere_le', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaires', to='core.agent')),
            ],
            options={
                'ordering': ['-date_debut'],
                'unique_together': {('agent', 'date_debut', 'date_fin')},
            },
        ),
    ]
