# Generated by Django 5.2.7 on 2026-01-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_reglesalaire_salaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='salaire_base_personnel',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override du salaire de base (si vide → règle générale)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='type_agent',
            field=models.CharField(choices=[('direction', 'Direction'), ('rot', 'Responsable Opérations'), ('entrepot', 'Superviseur'), ('terrain', 'Mamy'), ('agent_gros', 'Agent (Vente en Gros)'), ('stagiaire', 'Stagiaire')], max_length=50),
        ),
    ]
