# Generated by Django 5.2.7 on 2026-01-20 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_agent_salaire_base_personnel_alter_agent_type_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reglesalaire',
            old_name='salaire_base',
            new_name='dotation_fonction',
        ),
    ]
