# Generated by Django 5.2.7 on 2026-01-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_rename_salaire_base_reglesalaire_dotation_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='date_debut_fonction',
            field=models.DateField(blank=True, help_text='Date de prise de fonction (superviseur / agent)', null=True),
        ),
    ]
