# Generated by Django 6.0.1 on 2026-01-28 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_agent_date_debut_fonction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recouvrement',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'type_agent__in': ['terrain', 'agent_gros']}, on_delete=django.db.models.deletion.CASCADE, related_name='recouvrements', to='core.agent'),
        ),
    ]
