# Generated by Django 6.0.1 on 2026-01-28 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_alter_recouvrement_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationlotsuperviseur',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 28, 15, 54, 6, 956404, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affectationlotsuperviseur',
            name='date_affectation',
            field=models.DateField(verbose_name='Date de distribution'),
        ),
    ]
