# Generated by Django 6.0.1 on 2026-01-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_affectationlotsuperviseur_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectationlotsuperviseur',
            name='date_affectation',
            field=models.DateTimeField(verbose_name='Date de distribution'),
        ),
    ]
