# Generated by Django 6.0.1 on 2026-01-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_alter_affectationlotsuperviseur_date_affectation'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationlotsuperviseur',
            name='prix_detail',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affectationlotsuperviseur',
            name='prix_gros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
