# Generated by Django 5.2.7 on 2026-01-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_affectationlotsuperviseur_prix_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectationlotsuperviseur',
            name='prix_detail',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='affectationlotsuperviseur',
            name='prix_gros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
