# Generated by Django 5.2.7 on 2026-01-29 23:27

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_alter_affectationlotsuperviseur_prix_detail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributionagent',
            options={'ordering': ['-date_distribution']},
        ),
        migrations.AddField(
            model_name='depense',
            name='categorie',
            field=models.CharField(choices=[('ACHAT_MARCHANDISE', 'Achat marchandise'), ('TRANSPORT_MARCHANDISE', 'Transport marchandise'), ('CARBURANT', 'Carburant'), ('MAINTENANCE_VEHICULE', 'Maintenance véhicule'), ('FRAIS_OPERATIONNELS', 'Frais opérationnels'), ('TRANSFERT', 'Transfert'), ('DIVERS', 'Divers')], default='DIVERS', max_length=40, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='depense',
            name='note',
            field=models.CharField(blank=True, help_text='Détail libre saisi par l’agent', max_length=255, verbose_name='Note (optionnelle)'),
        ),
        migrations.AddField(
            model_name='depense',
            name='source',
            field=models.CharField(choices=[('ROT', 'Saisie terrain'), ('MIGRATION', 'Migration historique'), ('ADMIN', 'Correction admin')], default='ROT', max_length=20),
        ),
        migrations.AlterField(
            model_name='depense',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Description historique'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='versement',
            field=models.ForeignKey(blank=True, help_text='Versement éventuellement lié', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='core.versementbancaire'),
        ),
        migrations.AddIndex(
            model_name='distributionagent',
            index=models.Index(fields=['date_distribution'], name='core_distri_date_di_98b945_idx'),
        ),
        migrations.AddIndex(
            model_name='distributionagent',
            index=models.Index(fields=['superviseur'], name='core_distri_supervi_6eb028_idx'),
        ),
    ]
