# Generated by Django 5.2.7 on 2026-02-06 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_alter_distributionagent_options_depense_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementfournisseur',
            name='effectue_par',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_agent': 'rot'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_fournisseurs_rot', to='core.agent', verbose_name='Paiement effectué par (ROT)'),
        ),
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='superviseur',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_agent': 'entrepot'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_fournisseurs_superviseur', to='core.agent', verbose_name='Superviseur (déprécié – ancienne logique)'),
        ),
    ]
