# Generated by Django 5.2.7 on 2026-02-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_paiementfournisseur_effectue_par_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectationlotsuperviseur',
            name='date_affectation',
            field=models.DateField(verbose_name='Date de distribution'),
        ),
    ]
