# Generated by Django 5.2.7 on 2026-02-20 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_alter_affectationlotsuperviseur_date_affectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='date_depense',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de la dépense'),
        ),
    ]
