# Generated by Django 5.2.7 on 2026-02-20 13:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_alter_depense_date_depense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='date_depense',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de la dépense'),
        ),
    ]
