# Generated by Django 5.2.7 on 2026-04-20 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_alter_depense_date_depense'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotentrepot',
            name='quantite_disponible_rot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='agent',
            name='type_agent',
            field=models.CharField(choices=[('direction', 'Direction'), ('rot', 'Responsable Opérations'), ('entrepot', 'Superviseur'), ('terrain', 'Mamy'), ('agent_gros', 'Agent (Vente en Gros)'), ('stagiaire', 'Stagiaire'), ('gestionnaire_stock', 'Gestionnaire Stock')], max_length=50),
        ),
        migrations.CreateModel(
            name='MiseDispositionRot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('effectue_par', models.ForeignKey(limit_choices_to={'type_agent': 'gestionnaire_stock'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mises_disposition_effectuees', to='core.agent')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lotentrepot')),
            ],
        ),
    ]
