# Generated by Django 5.2.7 on 2026-04-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_lotentrepot_quantite_disponible_rot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='type_agent',
            field=models.CharField(choices=[('direction', 'Direction'), ('rot', 'Responsable Opérations'), ('entrepot', 'Superviseur'), ('terrain', 'Mami'), ('agent_gros', 'Agent Gros'), ('stagiaire', 'Stagiaire'), ('gestionnaire_stock', 'Gestionnaire Stock')], max_length=50),
        ),
    ]
