# Generated by Django 5.2.7 on 2026-05-02 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_alter_agent_type_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='type_agent',
            field=models.CharField(choices=[('direction', 'Direction'), ('rot', 'Responsable Opérations'), ('entrepot', 'Superviseur'), ('terrain', 'Mami'), ('agent_gros', 'Agent Gros'), ('agent_polivalent', 'Agent Polivalent'), ('stagiaire', 'Stagiaire'), ('gestionnaire_stock', 'Gestionnaire Stock')], max_length=50),
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('solde', 'Solde superviseur'), ('stock', 'Stock ancien'), ('prix', 'Variation prix'), ('activite', 'Baisse activité')], max_length=30)),
                ('niveau', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critique', 'Critique')], max_length=20)),
                ('message', models.TextField()),
                ('est_vue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_agent', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.produit')),
                ('superviseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_superviseur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
