# Generated by Django 5.2.7 on 2026-06-02 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_alter_agent_type_agent_alerte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recouvrement',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recouvrements', to='core.agent'),
        ),
    ]
