# Generated by Django 6.0.1 on 2026-06-10 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_alter_recouvrement_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectationlotsuperviseur',
            name='attribue_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_realisees', to='core.agent'),
        ),
    ]
