# Generated by Django 5.2.7 on 2026-06-16 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_alter_affectationlotsuperviseur_attribue_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturelotentrepot',
            name='paiement_fournisseur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture_associee', to='core.paiementfournisseur'),
        ),
    ]
