# Generated by Django 5.2.7 on 2026-06-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_facturelotentrepot_paiement_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturelotentrepot',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='factures_entrepot/%Y/%m/'),
        ),
    ]
