# Generated by Django 6.0.1 on 2026-07-08 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_alter_facturelotentrepot_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationlotsuperviseur',
            name='agent_terrain_direct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_directes', to='core.agent', verbose_name='Agent destinataire (distribution directe)'),
        ),
    ]
