# Generated by Django 6.0.1 on 2026-07-22 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_add_agent_terrain_direct_to_affectation'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='peut_faire_depense',
            field=models.BooleanField(default=False, help_text='Autorise la saisie de dépenses indépendamment du rôle (ROT ou superviseur).', verbose_name='Peut effectuer des dépenses'),
        ),
        migrations.AlterField(
            model_name='recouvrementsuperviseur',
            name='rot',
            field=models.ForeignKey(limit_choices_to={'type_agent__in': ['rot', 'direction']}, on_delete=django.db.models.deletion.CASCADE, related_name='recouvrements_superviseurs', to='core.agent'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agent'),
        ),
        migrations.AlterField(
            model_name='versementbancaire',
            name='effectue_par',
            field=models.ForeignKey(blank=True, help_text='ROT ou Direction ayant réellement effectué le versement', limit_choices_to={'type_agent__in': ['rot', 'direction']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements_effectues', to='core.agent'),
        ),
    ]
