# Generated by Django 6.0.1 on 2026-07-23 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_extend_finance_permissions_and_peut_faire_depense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versementbancaire',
            name='superviseur',
            field=models.ForeignKey(blank=True, help_text="(OBSOLÈTE) Ancien champ 'qui a effectué ce versement', remplacé par effectue_par — PAS une attribution de source du cash", limit_choices_to={'type_agent': 'entrepot'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements_bancaires', to='core.agent'),
        ),
    ]
