# Generated by Django 6.0.1 on 2026-07-27 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_clarify_versementbancaire_superviseur_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='date_dernier_envoi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerte',
            name='date_resolution',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerte',
            name='distribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='core.detaildistribution'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='core.lotentrepot'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='nombre_envois',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alerte',
            name='statut',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLUE', 'Résolue'), ('IGNOREE', 'Ignorée')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='type_alerte',
            field=models.CharField(choices=[('solde', 'Solde superviseur'), ('solde_persistant', 'Solde persistant'), ('stock', 'Stock ancien'), ('prix', 'Variation prix'), ('activite', 'Baisse activité')], max_length=30),
        ),
    ]
