# Generated by Django 6.0.1 on 2026-07-31 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_alerte_date_dernier_envoi_alerte_date_resolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versementbancaire',
            name='effectue_par',
            field=models.ForeignKey(blank=True, help_text='ROT ou Direction ayant réellement effectué le versement', limit_choices_to={'type_agent__in': ['rot', 'direction', 'gestionnaire_stock']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements_effectues', to='core.agent'),
        ),
    ]
