# Generated by Django 6.0.1 on 2026-08-03 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_alter_versementbancaire_effectue_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='perte',
            name='detail_distribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pertes', to='core.detaildistribution'),
        ),
    ]
