# Generated by Django 6.0.1 on 2026-08-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_perte_detail_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='commentaire_perte',
            field=models.CharField(blank=True, max_length=255, verbose_name="Commentaire de perte (produit à l'unité)"),
        ),
    ]
