# Generated by Django 6.0.1 on 2026-08-03 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_vente_commentaire_perte'),
    ]

    operations = [
        migrations.AddField(
            model_name='perte',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pertes_liees', to='core.vente'),
        ),
    ]
