# Generated by Django 6.0.1 on 2026-08-05 15:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_perte_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='reference_dams_agro',
            field=models.PositiveIntegerField(blank=True, help_text="ID de l'EngagementFinancier créé côté dams_agro via l'API /api/engagements/.", null=True, verbose_name='Référence dams_agro'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='categorie',
            field=models.CharField(choices=[('ACHAT_MARCHANDISE', 'Achat marchandise'), ('TRANSPORT_MARCHANDISE', 'Transport marchandise'), ('CARBURANT', 'Carburant'), ('MAINTENANCE_VEHICULE', 'Maintenance véhicule'), ('FRAIS_OPERATIONNELS', 'Frais opérationnels'), ('TRANSFERT', 'Transfert'), ('DIVERS', 'Divers'), ('AVANCE_CHAMP', 'Avance de trésorerie (champ)'), ('DEPENSE_CHAMP', 'Dépense pour le compte du champ')], default='DIVERS', max_length=40, verbose_name='Catégorie'),
        ),
        migrations.CreateModel(
            name='RemboursementChamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_remboursement', models.DateField(default=django.utils.timezone.localdate)),
                ('reference_dams_agro', models.PositiveIntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements_champ', to='core.depense')),
            ],
            options={
                'verbose_name': 'Remboursement (champ)',
                'verbose_name_plural': 'Remboursements (champ)',
                'ordering': ['-date_remboursement'],
            },
        ),
    ]
