# Generated by Django 6.0.1 on 2026-08-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_depense_reference_dams_agro_alter_depense_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerte',
            name='type_alerte',
            field=models.CharField(choices=[('solde', 'Solde superviseur'), ('solde_persistant', 'Solde persistant'), ('stock_entrepot', 'Stock dormant — entrepôt'), ('stock_superviseur', 'Stock en rétention — superviseurs'), ('stock_agent', 'Stock en rétention — agents'), ('prix', 'Ventes sous la marge minimale'), ('activite', "Baisse d'activité commerciale")], max_length=30),
        ),
    ]
