# Generated by Django 6.0.1 on 2026-08-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_alter_alerte_type_alerte'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotentrepot',
            name='cession_idempotency_key',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name="Clé d'idempotence de la cession source"),
        ),
    ]
