# Generated by Django 6.0.1 on 2026-08-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_lotentrepot_cession_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='perte',
            name='kilo_perdu_incentive',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kg perdus (incentive)'),
        ),
    ]
