# Generated by Django 6.0.1 on 2026-08-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_perte_kilo_perdu_incentive'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='taux_incentive',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="FCFA par unité vendue, indépendant du poids. Laisser vide pour que l'incentive de ce produit suive le taux au kg (RegleSalaire.incentive_par_kg).", max_digits=10, null=True),
        ),
    ]
