# Generated by Django 6.0.1 on 2026-09-08 12:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_produit_taux_incentive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransfertPortefeuilleAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(blank=True)),
                ('date_transfert', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_portefeuille_realises', to=settings.AUTH_USER_MODEL)),
                ('superviseur_cible', models.ForeignKey(limit_choices_to={'type_agent': 'entrepot'}, on_delete=django.db.models.deletion.CASCADE, related_name='transferts_portefeuille_entrants', to='core.agent', verbose_name='Superviseur cible')),
                ('superviseur_source', models.ForeignKey(blank=True, limit_choices_to={'type_agent': 'entrepot'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_portefeuille_sortants', to='core.agent', verbose_name='Superviseur source')),
            ],
            options={
                'verbose_name': "Transfert de portefeuille d'agents",
                'verbose_name_plural': "Transferts de portefeuille d'agents",
                'ordering': ['-date_transfert'],
            },
        ),
        migrations.CreateModel(
            name='LigneTransfertAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_distributions_basculees', models.PositiveIntegerField(default=0)),
                ('stock_bascule', models.JSONField(blank=True, default=list)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_portefeuille', to='core.agent')),
                ('transfert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.transfertportefeuilleagent')),
            ],
            options={
                'verbose_name': "Ligne de transfert d'agent",
                'verbose_name_plural': "Lignes de transfert d'agent",
                'unique_together': {('transfert', 'agent')},
            },
        ),
    ]
