# Generated by Django 6.0.1 on 2026-09-10 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_resoudre_alertes_stock_obsoletes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotSuperviseurAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_snapshot', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots_superviseur', to='core.agent')),
                ('superviseur', models.ForeignKey(blank=True, limit_choices_to={'type_agent': 'entrepot'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_agents_geres', to='core.agent')),
            ],
            options={
                'verbose_name': "Snapshot superviseur d'un agent",
                'verbose_name_plural': 'Snapshots superviseur des agents',
                'ordering': ['-date_snapshot'],
            },
        ),
    ]
