# Generated by Django 6.0.1 on 2026-09-15 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0121_snapshot_superviseur_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionAdministrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('type_correction', models.CharField(choices=[('LOT_QUANTITE', 'Quantité du lot'), ('LOT_PRIX', "Prix d'achat du lot"), ('LOT_DATE', 'Date de réception du lot'), ('DISTRIBUTION_AGENT', 'Agent destinataire de la distribution'), ('DISTRIBUTION_SUPERVISEUR', 'Superviseur de la distribution'), ('DISTRIBUTION_QUANTITE', 'Quantité distribuée'), ('VENTE_PRIX_QUANTITE', 'Prix et/ou quantité de la vente')], max_length=30)),
                ('motif', models.TextField()),
                ('anciennes_valeurs', models.JSONField()),
                ('nouvelles_valeurs', models.JSONField()),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correction administrative',
                'verbose_name_plural': 'Corrections administratives',
                'ordering': ['-date_action'],
            },
        ),
    ]
