# Generated by Django 6.0.1 on 2026-09-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_correction_administrative_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctionadministrative',
            name='motif',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='correctionadministrative',
            name='type_correction',
            field=models.CharField(choices=[('LOT_QUANTITE', 'Quantité du lot'), ('LOT_PRIX', "Prix d'achat du lot"), ('LOT_DATE', 'Date de réception du lot'), ('LOT_FOURNISSEUR', 'Fournisseur du lot'), ('DISTRIBUTION_AGENT', 'Agent destinataire de la distribution'), ('DISTRIBUTION_SUPERVISEUR', 'Superviseur de la distribution'), ('DISTRIBUTION_PRODUIT', 'Produit/lot distribué'), ('DISTRIBUTION_QUANTITE', 'Quantité distribuée'), ('DISTRIBUTION_DATE', 'Date de la distribution'), ('VENTE_PRIX_QUANTITE', 'Prix et/ou quantité de la vente'), ('VENTE_DATE', 'Date de la vente')], max_length=30),
        ),
    ]
