# Generated by Django 6.0.1 on 2026-09-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_correction_administrative_suppression_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerte',
            name='type_alerte',
            field=models.CharField(choices=[('solde', 'Solde superviseur'), ('solde_persistant', 'Solde persistant'), ('stock_entrepot', 'Stock dormant — entrepôt'), ('stock_superviseur', 'Stock en rétention — superviseurs'), ('stock_agent', 'Stock en rétention — agents'), ('prix', 'Ventes sous la marge minimale'), ('prix_ecart_achat', "Ventes à prix suspect (écart inhabituel avec le prix d'achat)"), ('activite', "Baisse d'activité commerciale")], max_length=30),
        ),
    ]
