# Generated by Django 6.0.1 on 2026-10-05 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_alter_alerte_type_alerte'),
    ]

    operations = [
        migrations.AddField(
            model_name='recouvrementsuperviseur',
            name='versement',
            field=models.ForeignKey(blank=True, help_text='Versement qui a regroupé cette remise (un versement peut couvrir plusieurs superviseurs)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recouvrements', to='core.versementbancaire', verbose_name='Versement bancaire associé'),
        ),
    ]
