# Generated by Django 6.0.1 on 2026-10-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_rattacher_recouvrements_versements'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['-date_vente', '-id'], name='vente_date_id_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['date_creation'], name='vente_date_creation_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['agent', '-date_vente'], name='vente_agent_date_idx'),
        ),
    ]
