# Generated by Django 6.0.1 on 2026-07-20 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0106_add_agent_terrain_direct_to_affectation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VwAnalyseStock',
            fields=[
                ('produit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('produit_nom', models.CharField(max_length=100, null=True)),
                ('fournisseur_id', models.IntegerField(null=True)),
                ('fournisseur_nom', models.CharField(max_length=100, null=True)),
                ('quantite_restante', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valeur_stock', models.DecimalField(decimal_places=2, max_digits=15)),
                ('jours_en_stock_moyen', models.DecimalField(decimal_places=1, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'bi_"."vw_analyse_stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwMargeFournisseur',
            fields=[
                ('fournisseur_mois_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fournisseur_id', models.IntegerField()),
                ('fournisseur_nom', models.CharField(max_length=100, null=True)),
                ('mois', models.DateField()),
                ('ca', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cout_achat_systeme', models.DecimalField(decimal_places=2, max_digits=15)),
                ('marge_systeme', models.DecimalField(decimal_places=2, max_digits=15)),
                ('marge_pct_systeme', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('prix_achat_corrige_pondere', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('calibre', models.BooleanField()),
                ('cout_achat_calibre', models.DecimalField(decimal_places=2, max_digits=15)),
                ('marge_calibree', models.DecimalField(decimal_places=2, max_digits=15)),
                ('marge_calibree_pct', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'bi_"."vw_marge_fournisseur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwPerformanceAgent',
            fields=[
                ('agent_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_complet', models.CharField(max_length=200)),
                ('type_agent', models.CharField(max_length=50)),
                ('kg_vendus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jours_actifs', models.IntegerField()),
                ('kg_par_jour', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('statut_objectif_50kg', models.CharField(max_length=20, null=True)),
                ('marge', models.DecimalField(decimal_places=2, max_digits=15)),
                ('incentive', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rentabilite_agent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ratio_incentive_marge_pct', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'bi_"."vw_performance_agent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwPerformanceSuperviseur',
            fields=[
                ('superviseur_id', models.IntegerField(primary_key=True, serialize=False)),
                ('superviseur_nom', models.CharField(max_length=200)),
                ('ca', models.DecimalField(decimal_places=2, max_digits=15)),
                ('marge_brute', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cout_equipe', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rentabilite_nette', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nb_agents_actifs', models.IntegerField()),
                ('ca_moyen_par_agent', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'bi_"."vw_performance_superviseur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwRentabiliteGlobale',
            fields=[
                ('mois', models.DateField(primary_key=True, serialize=False)),
                ('ca', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cout_achat', models.DecimalField(decimal_places=2, max_digits=15)),
                ('marge_brute', models.DecimalField(decimal_places=2, max_digits=15)),
                ('marge_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('cout_salaires', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cout_depenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rentabilite_nette', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'bi_"."vw_rentabilite_globale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwRentabiliteProduit',
            fields=[
                ('produit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('produit_nom', models.CharField(max_length=100)),
                ('ca', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cout_achat', models.DecimalField(decimal_places=2, max_digits=15)),
                ('marge', models.DecimalField(decimal_places=2, max_digits=15)),
                ('marge_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('quantite_vendue_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_moyen', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('rotation_stock', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'bi_"."vw_rentabilite_produit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AjustementPrixAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_lot', models.CharField(blank=True, default='', help_text='Traçabilité optionnelle vers core_lotentrepot.reference_lot (texte libre, pas de FK — le lot peut être introuvable ou mal identifié au moment de la saisie).', max_length=100)),
                ('annee', models.PositiveSmallIntegerField()),
                ('mois', models.PositiveSmallIntegerField()),
                ('quantite_concernee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_achat_corrige', models.DecimalField(decimal_places=2, max_digits=10)),
                ('justification', models.TextField()),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustements_prix_achat', to='core.fournisseur')),
                ('produit', models.ForeignKey(blank=True, help_text='Traçabilité optionnelle, non utilisé par vw_marge_fournisseur (grain fournisseur x mois).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustements_prix_achat', to='core.produit')),
                ('saisi_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustements_prix_achat_saisis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Ajustement prix d'achat",
                'verbose_name_plural': "Ajustements prix d'achat",
                'ordering': ['-date_saisie'],
            },
        ),
    ]
