# Generated by Django 6.0.1 on 2026-07-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VwDepensesCategorie',
            fields=[
                ('depense_categorie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mois', models.DateField()),
                ('categorie', models.CharField(max_length=40, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('montant_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'bi_"."vw_depenses_categorie',
                'managed': False,
            },
        ),
    ]
