# Generated by Django 6.0.1 on 2026-07-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0010_vwrentabilitejournaliere'),
    ]

    operations = [
        migrations.CreateModel(
            name='VwPerformanceAgentSemaine',
            fields=[
                ('agent_semaine_id', models.IntegerField(primary_key=True, serialize=False)),
                ('agent_id', models.IntegerField()),
                ('nom_complet', models.CharField(max_length=200)),
                ('type_agent', models.CharField(max_length=50)),
                ('superviseur_id', models.IntegerField(null=True)),
                ('superviseur_nom', models.CharField(max_length=200, null=True)),
                ('semaine', models.DateField()),
                ('kg_vendus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jours_actifs', models.IntegerField()),
                ('jours_ouvres', models.IntegerField(null=True)),
                ('kg_par_jour', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('statut_objectif_50kg', models.CharField(max_length=20, null=True)),
                ('marge', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'bi_"."vw_performance_agent_semaine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwPerformanceSuperviseurSemaine',
            fields=[
                ('superviseur_semaine_id', models.IntegerField(primary_key=True, serialize=False)),
                ('superviseur_id', models.IntegerField()),
                ('superviseur_nom', models.CharField(max_length=200)),
                ('semaine', models.DateField()),
                ('ca', models.DecimalField(decimal_places=2, max_digits=15)),
                ('marge_brute', models.DecimalField(decimal_places=2, max_digits=15)),
                ('kg_vendus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nb_agents_actifs', models.IntegerField()),
            ],
            options={
                'db_table': 'bi_"."vw_performance_superviseur_semaine',
                'managed': False,
            },
        ),
    ]
