# Generated by Django 6.0.1 on 2026-08-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0011_vwperformanceagentsemaine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FctStockAgent',
            fields=[
                ('stock_agent_id', models.IntegerField(primary_key=True, serialize=False)),
                ('detail_distribution_id', models.IntegerField()),
                ('agent_id', models.IntegerField()),
                ('superviseur_id', models.IntegerField(null=True)),
                ('lot_id', models.IntegerField()),
                ('produit_id', models.IntegerField(null=True)),
                ('produit_nom', models.CharField(max_length=100, null=True)),
                ('date_reception', models.DateField(null=True)),
                ('stock_restant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_restant_kg', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'bi_"."fct_stock_agent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwVentesAgentProduit',
            fields=[
                ('ventes_agent_produit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('agent_id', models.IntegerField()),
                ('produit_id', models.IntegerField(null=True)),
                ('produit_nom', models.CharField(max_length=100, null=True)),
                ('mois', models.DateField()),
                ('kg_vendus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ca_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('marge', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nombre_ventes', models.IntegerField()),
            ],
            options={
                'db_table': 'bi_"."vw_ventes_agent_produit',
                'managed': False,
            },
        ),
    ]
