# Generated by Django 6.0.1 on 2026-08-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0012_fctstockagent_vwventesagentproduit'),
    ]

    operations = [
        migrations.CreateModel(
            name='VwVentesAgentProduitSemaine',
            fields=[
                ('ventes_agent_produit_semaine_id', models.IntegerField(primary_key=True, serialize=False)),
                ('agent_id', models.IntegerField()),
                ('produit_id', models.IntegerField(null=True)),
                ('produit_nom', models.CharField(max_length=100, null=True)),
                ('semaine', models.DateField()),
                ('kg_vendus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ca_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('marge', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nombre_ventes', models.IntegerField()),
            ],
            options={
                'db_table': 'bi_"."vw_ventes_agent_produit_semaine',
                'managed': False,
            },
        ),
    ]
