name: 'dams_bi'
version: '1.0.0'
config-version: 2

profile: 'dams_bi'
require-dbt-version: ">=1.12.0,<1.13.0"

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  incentive_terrain_fcfa_par_kg: 25

models:
  dams_bi:
    staging:
      +materialized: view
    marts:
      +materialized: table
      aggregates:
        +materialized: view
